/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.juego;
/**
 *
 * @author yisus
 */
public class ventanaInicio extends javax.swing.JFrame {
    Mercado merca;
    Equipo equipo;
    /**
     * Creates new form ventanaMenu
     * @param merca
     * @param equipo
     */
    public ventanaInicio(Mercado merca,Equipo equipo) {
        initComponents();
        this.merca = merca;
        this.equipo = equipo;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonTerminar = new javax.swing.JButton();
        BotonEmpezar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonTerminar.setBackground(new java.awt.Color(102, 102, 102));
        BotonTerminar.setFont(new java.awt.Font("Unispace", 0, 30)); // NOI18N
        BotonTerminar.setText("SALIR");
        BotonTerminar.setBorder(null);
        BotonTerminar.setFocusPainted(false);
        BotonTerminar.addActionListener(this::BotonTerminarActionPerformed);
        getContentPane().add(BotonTerminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 130, 40));

        BotonEmpezar.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        BotonEmpezar.setText("JUGAR");
        BotonEmpezar.setAlignmentY(0.0F);
        BotonEmpezar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BotonEmpezar.setFocusPainted(false);
        BotonEmpezar.addActionListener(this::BotonEmpezarActionPerformed);
        getContentPane().add(BotonEmpezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 340, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/juego/imagenes/estadio.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEmpezarActionPerformed
        ventanaMenu ventana2 = new ventanaMenu(merca,equipo);
        ventana2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonEmpezarActionPerformed

    private void BotonTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTerminarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonTerminarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEmpezar;
    private javax.swing.JButton BotonTerminar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
