package com.mycompany.juego;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author yisus
 */
public class ventanaPlantilla extends javax.swing.JFrame {
    Equipo equipo;
    ventanaMenu menu;
   
    /**
     * Creates new form ventanaPlantilla
     * @param equipo
     * @param menu
     * @param botones
     */
    public ventanaPlantilla(Equipo equipo,ventanaMenu menu,ArrayList<JButton> botones) {
        initComponents();
        this.equipo = equipo;
        this.menu = menu;
        
        for (JButton b: botones){
            panelJugadoresP.add(b);
            panelJugadoresP.revalidate();
            panelJugadoresP.repaint();
        }
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        panelJugadoresP.setPreferredSize(new Dimension(330,1600));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPlantilla = new javax.swing.JPanel();
        portero = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelJugadoresP = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        delantero1 = new javax.swing.JLabel();
        delantero2 = new javax.swing.JLabel();
        defensa1 = new javax.swing.JLabel();
        defensa2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPlantilla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        portero.setBackground(new java.awt.Color(102, 102, 102));
        portero.setOpaque(true);
        portero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                porteroMouseClicked(evt);
            }
        });
        panelPlantilla.add(portero, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 160, 200));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        panelJugadoresP.setLayout(new java.awt.GridLayout(0, 2, 2, 0));
        jScrollPane1.setViewportView(panelJugadoresP);

        panelPlantilla.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 330, 650));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        panelPlantilla.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        panelPlantilla.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 10, 650));

        delantero1.setBackground(new java.awt.Color(102, 102, 102));
        delantero1.setOpaque(true);
        delantero1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delantero1MouseClicked(evt);
            }
        });
        panelPlantilla.add(delantero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 160, 200));

        delantero2.setBackground(new java.awt.Color(102, 102, 102));
        delantero2.setOpaque(true);
        delantero2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delantero2MouseClicked(evt);
            }
        });
        panelPlantilla.add(delantero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 160, 200));

        defensa1.setBackground(new java.awt.Color(102, 102, 102));
        defensa1.setOpaque(true);
        defensa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                defensa1MouseClicked(evt);
            }
        });
        panelPlantilla.add(defensa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 160, 200));

        defensa2.setBackground(new java.awt.Color(102, 102, 102));
        defensa2.setOpaque(true);
        defensa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                defensa2MouseClicked(evt);
            }
        });
        panelPlantilla.add(defensa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 160, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPlantilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPlantilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void delantero1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delantero1MouseClicked
        equipo.ponerTitular("DELANTERO1",delantero1);
    }//GEN-LAST:event_delantero1MouseClicked

    private void delantero2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delantero2MouseClicked
        equipo.ponerTitular("DELANTERO2",delantero2);
    }//GEN-LAST:event_delantero2MouseClicked

    private void defensa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defensa1MouseClicked
        equipo.ponerTitular("DEFENSA1",defensa1);
    }//GEN-LAST:event_defensa1MouseClicked

    private void defensa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defensa2MouseClicked
        equipo.ponerTitular("DEFENSA2",defensa2);
    }//GEN-LAST:event_defensa2MouseClicked

    private void porteroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_porteroMouseClicked
        equipo.ponerTitular("PORTERO",portero);
    }//GEN-LAST:event_porteroMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel defensa1;
    private javax.swing.JLabel defensa2;
    private javax.swing.JLabel delantero1;
    private javax.swing.JLabel delantero2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelJugadoresP;
    private javax.swing.JPanel panelPlantilla;
    private javax.swing.JLabel portero;
    // End of variables declaration//GEN-END:variables
}
