package com.mycompany.juego;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTextField;
/**
 *
 * @author Monje
 */
public class ventanaCompra extends javax.swing.JFrame {
    ventanaMercado mercado;
    Equipo equipo;
    Jugador jugador;
    JTextField texto;
    JButton boton;
    JPanel panel;
    SistemaFacade fachada;
    /**
     * Creates new form ventanaCompra
     * @param mercado
     * @param equipo
     * @param j
     * @param texto
     * @param boton
     * @param panel
     */
    public ventanaCompra(ventanaMercado mercado,Equipo equipo,Jugador j,JTextField texto,JButton boton,JPanel panel) {
        initComponents();
        this.mercado = mercado;
        this.equipo = equipo;
        this.fachada = new SistemaFacade(equipo);
        this.jugador = j;
        this.texto = texto;
        this.boton = boton;
        this.panel = panel;
        botonComprar.setText(String.valueOf(j.getPrecio()));
        textoCompra.setText("Quieres comprar a " + j.getNombre() + "?");
        setLocationRelativeTo(this.mercado);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoCompra = new javax.swing.JLabel();
        botonComprar = new javax.swing.JButton();
        botonNOComprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        textoCompra.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        textoCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoCompra.setToolTipText("");

        botonComprar.setBackground(new java.awt.Color(0, 255, 0));
        botonComprar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        botonComprar.setText("SI");
        botonComprar.setFocusable(false);
        botonComprar.addActionListener(this::botonComprarActionPerformed);

        botonNOComprar.setBackground(new java.awt.Color(255, 0, 51));
        botonNOComprar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        botonNOComprar.setText("NO");
        botonNOComprar.setFocusable(false);
        botonNOComprar.addActionListener(this::botonNOComprarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(botonComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(botonNOComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
            .addComponent(textoCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonComprar, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(botonNOComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprarActionPerformed
        texto.setText(fachada.comprarJugador(jugador,mercado,boton,panel));
        this.dispose();
    }//GEN-LAST:event_botonComprarActionPerformed

    private void botonNOComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNOComprarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonNOComprarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComprar;
    private javax.swing.JButton botonNOComprar;
    private javax.swing.JLabel textoCompra;
    // End of variables declaration//GEN-END:variables
}
